### PR TITLE
Remove util.extension

### PR DESCRIPTION
**Pull request by Hakuyume**
- [x] add tests for current APIs
- [ ] change APIs
- [ ] update docs (if needed)

### CODE REVIEW

**Comment by yuyu2172** [comment]
We can delete utils.extensions.

**Comment by Hakuyume** [comment]
> We can delete utils.extensions since it is no longer necessary after #144.

Yes, extensions get more simple after #144. I changed this PR for removing `utils.extension`.

**Comment by Hakuyume** [comment]
@yuyu2172 Could you check this PR?

**Comment by yuyu2172** [comment]
LGTM

**Pull request merged**
