### PR TITLE
Consistency of citations

### PR DESCRIPTION
**Pull request by Hakuyume**

### CODE REVIEW

**Comment by yuyu2172** [comment]
Why do you put references above arguments in some and below in the others?

For instance, `pca_lightning` puts references above its arguments.

**Comment by yuyu2172** [comment]
Personally, references should be put above the arguments because that is how the compiled doc looks like.

**Comment by Hakuyume** [comment]
> Why do you put references above arguments in some and below in the others?

It was just my mistake. I tried to put all references below arguments.

> In my opinion, references should be put above the arguments because that is how the compiled doc looks like.

OK, I will change.

**Comment by yuyu2172** [comment]
LGTM

**Pull request merged**
