### PR TITLE
Add MultipleDataset

### PR DESCRIPTION
**Pull request by Hakuyume**
I added `MultipleDataset`. This dataset works as a concatenated dataset. I will add a doc.

### CODE REVIEW

**Comment by yuyu2172** [comment]
Thanks for PR!
I rally like the feature you support. However, I think that it is more appropriate to add this dataset to main Chainer repositiory because the functionality is more general to contain in ChainerCV.

FYI, it is perfectly fine to declare a class like this inside a train script when writing a example code.

**Comment by yuyu2172** [comment]
Also, I like `MergeDataset` than `MultipleDataset`. `Merge` conveys a message that multiple datasets are put together into one.

**Comment by Hakuyume** [comment]
I think `TransformDataset` is as general as `MultipleDataset`. It also can be used for general tasks. How do you think of it?
Anyway, as you pointed out, this dataset is not only for CV. I agree that it is better to add this dataset to Chainer. I will close this PR.
I agree that the name is not good. I am thinking to use `MergeDataset` or `ConcatenatedDataset`.

**Comment by yuyu2172** [comment]
I agree with you that `TransformDataset` is general enough to be integrated into Chainer.

As you suggested, I sent PR. https://github.com/pfnet/chainer/pull/2513

**Pull request closed without merging**
